name: CI Pipeline

on:
  push:
    branches:
      - main 
  pull_request:
    branches:
      - main 

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Garantir permissões de execução para Jest
        run: chmod +x node_modules/.bin/jest

      - name: Instalar dependências
        run: npm ci

      - name: Run tests
        run: npm test


